---
- name: Installing Database Servers
  hosts: dbservers
  become: yes
    #vars:
   # dbname: electric
   # dbuser: current
   # dbpass: tesla

  tasks:
    - debug:
         msg: "the dbname is {{dbname}}"

    - debug:
        var: dbuser

    - name: Installing mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install python3-PyMySQL
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present      

    - name: Starting the mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name "{{dbname}}"
      community.mysql.mysql_db:  # correct module name
        name: accounts
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database 
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        encrypted: no
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        plugin: mysql_native_password
        column_case_sensitive: false
      register: dbout

    - name:
      debug:
         var: dbout   

