---
- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP agent on CentOS
      yum:
        pkg: chrony
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install NTP agent on Ubuntu
      apt:
        pkg: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable NTP service on CentOS
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start and enable NTP service on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Copy using inline content
      copy:        
        content: '# This server is managed by ansible. No manual changes please'
        dest: /etc/motd

    - name: Deploy ntp agent on centos
      template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
 
    - name: Deploy ntp agent on ubuntu
      template:
        src: templates/ntpconf_ubantu
        dest: /etc/ntpsec/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"
        
    - name: restart service on centos
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"      

    - name: restart service on ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"
        
    - name: create a folder
      file: 
        path: /opt/test21
        state: directory  
