---
- name: Installing Webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Installing httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Starting the httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

- name: Installing Database Servers
  hosts: dbservers
  become: yes
  tasks:
    - name: Installing mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Starting the mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes


