---
- name: Understanding vars
  hosts: all
  become: yes 
  vars:
     USRNM: plausuer
     COMM: variable from playbokk

  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: dbout

    - debug:
        var: dbout.name

    - debug:
        var: dbout.comment
