---
- name: Provisioning Server
  hosts: all
  become: yes
  roles:
    - geerlingguy.java
    - role: post-install
      vars:
        ntp0: 0.in.pool.ntp.org
        ntp1: 0.in.pool.ntp.org
        ntp2: 0.in.pool.ntp.org
        ntp3: 0.in.pool.ntp.org
